### ISSUE TITLE
clang-format check

### ISSUE THREAD

**Issue by thejohnfreeman** [ripple/rippled#3266] opened 2020-02-21 01:33 UTC
To make sure committed code stays formatted (after we push a major reformat #3178), we should add a CI job that:

1. runs clang-format on `src/{ripple,test}/**/*.{h,cpp}`
2. asserts the git diff is empty

Until we make it easy for people to format the code, e.g. with a git commit hook, we shouldn't let this job block reviews from approval. Can we mark a job optional in Travis, @mellery451? If we can make the job non-blocking, then we can go ahead and develop and add it now, independent of the format PR.

**Comment by mellery451** [comment] 2020-02-21 05:39
a job can be marked as [allowed to fail](https://gitlab.ops.ripple.com/xrpledger/rippled-packages/snippets/49) so that it's status won't impact the overall job status - is that what you meant? Or did you mean non-blocking as in doesn't impact the running of other jobs?

**Comment by thejohnfreeman** [comment] 2020-02-21 15:01
That's what I meant. Non-blocking as in doesn't block the merge.

**Comment by cjcobb23** [comment] 2020-02-21 16:32
@thejohnfreeman do you think we should do this via github actions or travis?

**Comment by cjcobb23** [comment] 2020-02-21 18:26
@thejohnfreeman I rigged up a github action for this: https://github.com/cjcobb23/rippled/blob/develop/.github/workflows/ccpp.yml
Seems to be working

**Comment by nbougalis** [comment] 2020-04-29 21:14
Can this issue be closed, @thejohnfreeman, @cjcobb23?

**Comment by cjcobb23** [comment] 2020-04-29 22:19
> Can this issue be closed, @thejohnfreeman, @cjcobb23?

The github action is in `develop` and seems to be working as intended, so I think yes we can close this, but @thejohnfreeman should chime in to say for sure.

**Closed** 2020-12-06 22:18 UTC
Labels: CI
