### ISSUE TITLE
online_delete isn't working (Version: 1.7.2)

### ISSUE THREAD

**Issue by Brightside56** [ripple/rippled#3900] opened 2021-08-09 16:19 UTC
## Issue Description
Can't get working online_delete. ledger_history is 200000, online_delete is 200000, advisory_delete is 0. According docs and online delete logic: if node has more then 400000 complete ledgers (or so, maximum), old ledgers shouldn't accumulate anymore and disk space from old ledgers should be reused for new downloading ledgers. But instead my node has more than 500k complete ledgers and increasing :(

## Expected Result
online_delete is working, storage used isn't growing, old ledgers are rewritten with new ones.

## Actual Result
Node is syncing normally. Storage usage is growing, oldest complete ledger version isn't changing for more than 24h. Completed ledgers interval is growing
```
$ rippled --conf /srv/rippled.cfg server_state | grep "complete"
Loading: "/srv/rippled.cfg"
2021-Aug-09 16:17:32.085620208 UTC HTTPClient:NFO Connecting to 127.0.0.1:5005

         "complete_ledgers" : "65126677-65541537",
```

## Environment
CentOS 7 docker container with rippled 1.7.2
AWS EC2 m5.xlarge instance with EBS gp3 (16GB RAM, 4 CPU cores)
RocksDB as storage

## Config file (credentials masked)
```
[server]
port_rpc
port_peer

[port_rpc]
port = 5005
ip = 0.0.0.0
admin = 127.0.0.1
protocol = http
user = xxx
password = yyy

[port_peer]
port = 51235
ip = 0.0.0.0
protocol = peer
user = xxx
password = yyy
[ledger_history]
200000

[node_size]
medium

[node_db]
type=RocksDB
path=/srv/ripple/db/rocksdb
online_delete=200000
open_files=2048
filter_bits=12
cache_mb=4096
file_size_mb=64
file_size_mult=2
advisory_delete=0

[fetch_depth]
256

[database_path]
/srv/ripple/db

[debug_logfile]
/srv/ripple/debug.log

[sntp_servers]
time.windows.com
time.apple.com
time.nist.gov
pool.ntp.org

[validator_list_sites]
https://vl.ripple.com

[validator_list_keys]
ED2677ABFFD1B33AC6FBC3062B71F1E8397C1505E1C42C64D11AD1B28FF73F4734

[rpc_startup]
{ "command": "log_level", "severity": "warning" }
```

**Comment by cjcobb23** [comment] 2021-08-10 18:07
Hi. Is your earliest ledger still `65126677`? Just checking since it's been a day.

Can you grep the logs for the string `rotating`?

**Comment by Brightside56** [comment] 2021-08-10 18:36
@cjcobb23 it was last ledger more that a day. There was no rotating records in logs. Since I've edited config options a lot, I've decided to remove blockchain directory and start from scratch. I've set online_delete/ledger_history to 2000 and started node, after some time it started to rotate old ledgers with new ones (with 2000 value and with 2000 complete ledgers stored locally it takes probably hour or two). After that I've increased online_delete/ledger_history to 30000 to check how soon after backfilling it will start to rotate. Few hours passed, I have `"complete_ledgers" : "65532819-65566757"`, but it doesn't start rotation.

Probably it's working, but mechanism isn't clear for me(

**Comment by Brightside56** [comment] 2021-08-11 11:06
@cjcobb23 , same here, after increasing value of online_delete and ledger_history yesterday ledgers stop to rotate. Will wait one more day
```
rippled --conf /srv/rippled.cfg server_state | grep "complete"
Loading: "/srv/rippled.cfg"
2021-Aug-11 11:04:23.504646128 UTC HTTPClient:NFO Connecting to 127.0.0.1:5005

         "complete_ledgers" : "65532819-65582537",
```

**Comment by ximinez** [comment] 2021-08-11 16:15
The code that makes the decision whether to start rotating ledgers is at https://github.com/ripple/rippled/blob/1.7.2/src/ripple/app/misc/SHAMapStoreImp.cpp#L382-L384
```
        if (validatedSeq >= lastRotated + deleteInterval_ &&
            canDelete_ >= lastRotated - 1 && !health())
```
There are three parts to the condition:
1. The current validated ledger sequence must be at least as high as the sequence of the last rotated ledger plus the configured interval.
2. If `advisory_delete` is set, then the `can_delete` value must be high enough to allow rotation.
3. The node must be "healthy". Without going into detail, healthy basically means that the node is fully synced to the network, and has a recent validated ledger.

The least intuitive component of those rules is "the sequence of that last rotated ledger" (AKA `lastRotated`). If a rotation has never been successfully run, then the first time a ledger is fully validated, `lastRotated` will be initialized to it's sequence. After a successful rotation, `lastRotated` is updated to the sequence of the validated ledger when the rotation started.

So for example, if `online_delete = 20000` and you have ledgers "65532819-65582537", but the last rotation was completed on ledger 65580000, then the next rotation won't trigger until you have ledger 65580000+20000 = 65600000, which might take a while. The important thing is that it is completely irrelevant how many ledgers you already have - so the fact that the current range has almost 50,000 ledgers doesn't matter. In practice, with a healthy cadence of rotation, the node won't usually get much more than double the online_delete value, but if the node is struggling, or if you change the configuration, you can easily get these kinds of results.

Now that I've explained all of that, the most likely condition is that your node is simply not "healthy" enough to start. The second most likely is that the last rotation was later than you think. Grep your logs for the string "SHAMapStore". Most likely the last entry will look like either:
1. "Not deleting. state: full. age 68s". This one means your node is not healthy. If you see this error consistently, your node's hardware is probably not sufficient to run rippled reliably.
2. "finished rotation 65553382". This one means that a rotation has previously succeeded, and more importantly indicates the validated ledger sequence when it finished, which means that is now the value of `lastRotated`. Add that value to your `online_delete` interval to obtain the sequence of the validated ledger you should expect the next rotation to be attempted.

If you don't see any messages, then the problem is most likely that your log level is set too low, or you're rotating your logs, and those messages are in an old log file.

**Comment by Brightside56** [comment] 2021-08-11 20:27
@ximinez Allright. Rotation has started, in all cases it started when node has online_delete x2 completed ledgers. Node isn't struggling, it runs smoothly and always is in sync. Atop shows that disk io margin is enough. Understandable, but at same time such usage of resources is not very rational. I need to store 340k of ledgers, but node will store 680k in edge cases( Also most probably this will affect RocksDB performance, because it will require more disk io for 680k of ledgers than for 340k.

**Comment by ximinez** [comment] 2021-08-12 22:19
@Brightside56 I'm glad to hear that the rotation has started. I'm not quite sure what you mean about needing 340k ledgers. If you're saying that your config has `online_delete = 340000`, then the expected behavior is that the node will have _at least_ 340000 ledgers stored (unless the node is starting fresh or loses sync or similar). One common point of confusion with `online_delete` is that the ledgers are not stored in, for example, a sliding window or something like that, where a few are deleted at a time as new ledgers come in. The data isn't structured that way.

It would be more accurate to think of `online_delete` as storing ledgers in two "buckets". There's an old bucket which has (at least) 340k ledgers in it, and there's a new bucket which starts empty, and is where all the newly validated ledgers get stored. When the new bucket gets "full" - that is, it has 340k ledgers in it - the old bucket gets thrown out, the new bucket becomes the old bucket, and an empty new bucket gets put in place for the next round. This process is not instantaneous or atomic, so there is a delay from the time that the old bucket starts getting thrown out during which more ledgers may be put into the new bucket before the new new bucket is created. By necessity, that means that you'll usually have at least 340k ledgers stored, and the deletion process won't start until you have 680k (or more), when both buckets are full.

**Closed** 2021-08-20 22:51 UTC
