### ISSUE TITLE
Make pseudo transactions queryable

### ISSUE THREAD

**Issue by carlhua** [ripple/rippled#3440] opened 2020-06-04 12:51 UTC
## Summary

SetFee and EnableAmendment transactions show up in the ledger, but querying for them via tx_hash returns 'not found' - the updated version of the XRPL transaction explainer queries transactions directly from rippled, so it would be ideal to be able to fetch these as well.

Exported from RIPD-1742

**Comment by mDuo13** [comment] 2020-06-09 21:26
Duplicate of #2597 which has been fixed as of v1.5.0

**Closed by mDuo13** 2020-06-09 21:26 UTC
Labels: Feature Request, RIPD Export
