### ISSUE TITLE
DBG Ledger not found: order by LedgerSeq desc limit 1

### ISSUE THREAD

**Issue by zwht** [ripple/rippled#3878] opened 2021-07-02 12:51 UTC
help me

I have started the stand-alone Mode, multiple transfer records. After the service is stopped, how to keep the previous transaction records when the stand-alone Mode is restart

Start a New Genesis Ledger in Stand-Alone Mode
```javascript
rippled -a --start --conf=/etc/opt/ripple/rippled.cfg
```

Stop  Ledger
```javascript
rippled stop --conf=/etc/opt/ripple/rippled.cfg 
```

Load a Saved Ledger in Stand-Alone Mode

```javascript
rippled -a --load --conf=/etc/opt/ripple/rippled.cfg 
```

Error
```
2021-Jul-02 12:36:59.941750388 UTC Amendments:DBG Amendment B6B3EEDC0267AB50491FDC450A398AF30DBCD977CECED8BEF2499CAB5DAC19E2 is supported.
2021-Jul-02 12:36:59.941923834 UTC Application:NFO Loading specified Ledger
2021-Jul-02 12:36:59.942015302 UTC Ledger:DBG Ledger not found: order by LedgerSeq desc limit 1
2021-Jul-02 12:36:59.942033788 UTC Application:ERR The specified ledger could not be loaded.
```

rippled.cfg
```javascript
[server]
port_rpc_admin_local
port_ws_public

[port_rpc_admin_local]
port = 5005
ip = 0.0.0.0
admin = 0.0.0.0
protocol = http

[port_ws_public]
port = 6005
ip = 0.0.0.0
protocol = ws

[peer_private]
1

[node_size]
medium

[node_db]
type=nudb
path=/var/lib/rippled/db/nudb
online_delete=5120000
advisory_delete=0


[database_path]
/var/lib/rippled/db


[debug_logfile]
/var/log/rippled/debug.log

[sntp_servers]
time.windows.com
time.apple.com
time.nist.gov
pool.ntp.org


[rpc_startup]
{ "command": "log_level", "severity": "warning" }

[ssl_verify]
0

```

**Comment by cjcobb23** [comment] 2021-07-02 14:47
Try running this command after starting and before stopping:
```
rippled ledger_accept --conf=/etc/opt/rippled.cfg
```

**Comment by zwht** [comment] 2021-07-02 14:52
> 尝试在启动后和停止前运行此命令：
> 
> ```
> rippled ledger_accept --conf=/etc/opt/rippled.cfg
> ```

我试过，从创世钱包转账到另外一个钱包，然后手动ledger_accept，然后在stop

rippled ledger_accept --conf=/etc/opt/ripple/rippled.cfg

**Comment by zwht** [comment] 2021-07-02 14:54
> Try running this command after starting and before stopping:
> 
> ```
> rippled ledger_accept --conf=/etc/opt/rippled.cfg
> ```

I have tried transferring money from creation wallet to another wallet, then manually ledger_accept, and then stop. It doesn't work yet
rippled ledger_accept --conf=/etc/opt/ripple/rippled.cfg

**Comment by ximinez** [comment] 2021-07-02 14:58
> After the service is stopped, how to keep the previous transaction records when the stand-alone Mode is restart

Standalone mode starts completely fresh every time. It does not write anything to disk. This is by design and there is no way to change it. Once you stop it, everything you've done is gone.

If your intention is to test locally without connecting to any networks, remove any validator list information from validators.cfg and rippled.cfg, then configure your node with database paths, etc, and define a `[validation_seed]` so it will run as a validator. Once that's done, run `rippled` without the `-a` option. It should participate in consensus by itself, make forward progress, and write ledgers to disk. One downside is that you will not be able to use the `ledger_accept` command to control the timing of ledger closing.

> `rippled -a --load --conf=/etc/opt/ripple/rippled.cfg`

The `--load` option loads the latest ledger from the local DB on disk. If you have never run rippled in non-standalone, there will be nothing on disk to load.

**Comment by zwht** [comment] 2021-07-02 15:02
> > 服务停止后，单机模式重启时如何保持之前的交易记录
> 
> 独立模式每次都以全新的方式启动。它不会向磁盘写入任何内容。这是设计使然，没有办法改变它。一旦你停止它，你所做的一切都没有了。
> 
> 如果您打算在不连接任何网络的情况下进行本地测试，请从 validators.cfg 和rippled.cfg 中删除任何验证器列表信息，然后使用数据库路径等配置您的节点，并定义一个`[validation_seed]`使其作为验证器运行。完成后，在`rippled`没有`-a`选项的情况下运行。它应该自己参与共识，向前推进，并将账本写入磁盘。一个缺点是您将无法使用该`ledger_accept`命令来控制分类帐关闭的时间。
> 
> > `rippled -a --load --conf=/etc/opt/ripple/rippled.cfg`
> 
> 该`--load`选项从磁盘上的本地数据库加载最新的分类帐。如果您从未在非独立模式下运行过rippled，那么磁盘上将没有任何东西可以加载。

Thank you, perfect

**Comment by zwht** [comment] 2021-07-02 15:03
> > After the service is stopped, how to keep the previous transaction records when the stand-alone Mode is restart
> 
> Standalone mode starts completely fresh every time. It does not write anything to disk. This is by design and there is no way to change it. Once you stop it, everything you've done is gone.
> 
> If your intention is to test locally without connecting to any networks, remove any validator list information from validators.cfg and rippled.cfg, then configure your node with database paths, etc, and define a `[validation_seed]` so it will run as a validator. Once that's done, run `rippled` without the `-a` option. It should participate in consensus by itself, make forward progress, and write ledgers to disk. One downside is that you will not be able to use the `ledger_accept` command to control the timing of ledger closing.
> 
> > `rippled -a --load --conf=/etc/opt/ripple/rippled.cfg`
> 
> The `--load` option loads the latest ledger from the local DB on disk. If you have never run rippled in non-standalone, there will be nothing on disk to load.

Thank you, perfect

**Comment by ximinez** [comment] 2021-07-02 15:09
> Thank you, perfect

You're welcome! I'm going to close this ticket now. Please feel free to reopen it if you have further related questions or problems.

**Closed by ximinez** 2021-07-02 15:09 UTC

**Comment by zwht** [comment] 2021-07-02 16:05
remove any validator list information
define a [validation_seed]
```
 rippled --start --conf=/etc/opt/ripple/rippled.cfg
```
the genesis address no XRP

my rippled.cfg

```

[server]
port_rpc_admin_local
port_peer
port_ws_admin_local

[port_rpc_admin_local]
port = 8000
ip = 127.0.0.1
admin = 127.0.0.1
protocol = http

[port_peer]
port = 40000
ip = 0.0.0.0
protocol = peer


[port_ws_admin_local]
port = 6006
ip = 0.0.0.0
admin = 0.0.0.0
protocol = ws

[peer_private]
1

[node_size]
medium

[node_db]
type=NuDB
path=/var/lib/rippled/db/nudb
online_delete=5120000
advisory_delete=0

[database_path]
/var/lib/rippled/db

[debug_logfile]
/var/log/rippled/debug.log

[sntp_servers]
time.windows.com
time.apple.com
time.nist.gov
pool.ntp.org


[validation_seed]
snMpsBybpoDtf6JjF4W6PuH3uQK6P

[validators]
n9LigqrcDkSMcjidYjxSFhRo7vz1VRSRjBmiHvf5RZxJa7SvVsRV


[rpc_startup]
{ "command": "log_level", "severity": "debug" }

[ssl_verify]
0

```

**Comment by zwht** [comment] 2021-07-02 16:12
> > 谢谢，完美
> 
> 别客气！我现在要关闭这张票。如果您有进一步的相关问题或问题，请随时重新打开它。

help me

**Comment by zwht** [comment] 2021-07-02 16:13
> > Thank you, perfect
> 
> You're welcome! I'm going to close this ticket now. Please feel free to reopen it if you have further related questions or problems.

help me

**Comment by ximinez** [comment] 2021-07-02 18:06
We don't really provide support for private or alternative networks. It sounds like you may be better off connecting to the Test Net or Dev Net. Instructions are at https://xrpl.org/connect-your-rippled-to-the-xrp-test-net.html
