### ISSUE TITLE
How can I set destination tag to new account ? (Version: 1.6)

### ISSUE THREAD

**Issue by block-hac** [ripple/rippled#3704] opened 2020-12-15 15:16 UTC
## Summary

I created new xrp account by using generateAddress() of ripple-lib.
## Motivation

To deposit XRP, I need to get destination_tag of new account.
## Solution

How can I get or set destination_tag from new account ?

**Comment by ximinez** [comment] 2020-12-15 16:43
Duplicate of #3664: "How to get XRP account tag ?"

@intelliot wrote:
> For an account that you own, the destination tag is an arbitrary 32-bit unsigned integer. It is additional data that is embedded in a transaction.
> 
> If you generated the new account with `api.generateAddress()`, you can use any tag that you want. It just needs to be a 32-bit unsigned integer, so the minimum value is `0` and the maximum is `4294967295`. You can choose any number within that range.
>
> > Source tags and destination tags are a feature of XRP Ledger payments that can indicate specific purposes for payments from and to multi-purpose addresses. Source and destination tags do not have direct on-ledger functionality; source and destination tags merely provide information about how off-ledger systems should process a payment.
> - [Source and Destination Tags - xrpl.org](https://xrpl.org/source-and-destination-tags.html)
> 
> Typically, services like exchanges use tags to identify which client a particular deposit is intended for.
>
> One rough analogy: When you own an account on the XRP Ledger, you could think of yourself as a "bank." Your account's classic address is the routing number, and the tag is the account number. Since you are the "bank," you have to determine, assign, and handle the account numbers (tags).
>
> Does this help?

And I wrote:
> Note, though, that tags are optional by default. If the account you're creating is personal, and doesn't need any of the types of divisions and record-keeping provided by destination tags, you don't need to use them.

**Closed by ximinez** 2020-12-15 16:43 UTC
Labels: Feature Request
