### ISSUE TITLE
Get rid of old account_tx call

### ISSUE THREAD

**Issue by carlhua** [ripple/rippled#3467] opened 2020-06-30 12:20 UTC
Because the old account_tx semantics still appear to work, developers may use them and get unexpected results. Worse, this can make the new semantics appear not to work because the old semantics are selected inadvertently. The old semantics are known to be broken and have been deprecated.

The old semantics still appear in several places:
https://github.com/ripple/ripple-rest/blob/develop/api/payments.js#L408
And likely other places as well.

Any account_tx request that includes the following fields needs to change to use the new API:
offset, count, descending, ledger_max, ledger_min

We should remove the old API from rippled entirely.
Exported from RIPD-689

**Comment by mDuo13** [comment] 2021-03-02 03:48
Duplicate of #2926.

**Closed by mDuo13** 2021-03-02 03:48 UTC
Labels: RIPD Export, Tech Debt
