### ISSUE TITLE
mirrors.ripple.com keyexpired?

### ISSUE THREAD

**Issue by gituser** [ripple/rippled#2077] opened 2017-04-04 15:29 UTC
Hello.

Trying to compile ripple on Ubuntu 14.04 LTS and getting this after running `Builds/Ubuntu/install_rippled_depends_ubuntu.sh`:

```W: GPG error: https://mirrors.ripple.com trusty InRelease: The following signatures were invalid: KEYEXPIRED 1461800239 KEYEXPIRED 1461800239 KEYEXPIRED 1461800239 KEYEXPIRED 1461800239```

Something wrong with the signing key ? Can you guys update the signing key?

`apt-key list|grep -i expired` doesn't show any expired keys

ca-certificates package is installed, what could be the issue?

i've also checked date it's fine, so it has to be something to do with your signing key.

Thanks.

**Comment by ximinez** [comment] 2017-04-04 16:07
@gituser Thanks for the reporting this. We're looking in to it now.

**Comment by wilsonianb** [comment] 2017-04-04 22:55
Hi @gituser, this should be fixed now.

You can also use these instructions to install rippled instead of compiling:
https://ripple.com/build/rippled-setup/#installation-on-ubuntu-with-alien

The limitation on Ubuntu 14.04 is that you can't run as a systemd service (steps 6 & 7).

**Comment by gituser** [comment] 2017-04-04 23:47
Thanks for the fix. I'll try a little bit later in 14.04.
I gave up on 14.04 because I was having other issues there and went to the 16.04 where I compiled fine rippled without even using external repositories.

**Comment by MarkusTeufelberger** [comment] 2017-04-05 08:49
@wilsonianb - are these binaries sufficiently hardened (e.g. enabling ASLR, fortifying source, PIE, stack protectors etc.)? See https://wiki.debian.org/Hardening for more info.

Are they built in a reproducible way and where can one find a signed hash of the build artifacts, similar to what Bitcoin does with Gitian builds?

Who has access to this repository? If people are running this auto-updater script, they are under very serious risk if your repository gets compromised. This includes pushing alternative validator.txt files, potentially to validators.

**Comment by nbougalis** [comment] 2017-04-26 19:21
@gituser: no, there are no plans at this time to support building on Jessie. It doesn't have a recent-enough version of gcc by default, and Stretch is just around the corner.

@MarkusTeufelberger: we do not have reproducible builds yet, but plan on adding that functionality, likely using `gitian`. On the topic of hardening: we do some, but we can likely add more - I will investigate that. As for repo security: there's a manual process involved currently, and we do have some security measures in place that should make a comrpomise extremely unlikely. That said, I will work with our ops team to make sure that there isn't something obvious we could be doing that we aren't. I will create issues for reproducile builds and source-hardening separately.

I'm closing this for now. If you think concerns haven't been addressed, please feel free to reopen.

**Closed by nbougalis** 2017-04-26 19:21 UTC

**Comment by MarkusTeufelberger** [comment] 2017-04-27 09:14
Thanks, at least from an outside perspective this looks more critical that it might be intended or expected, especially the auto-updater.

I hope you'll also evaluate Bazel, which adds a few nice properties like hermetic and incremental builds next to reproducibility. This might also help to get rid of these "unity" builds.
