### ISSUE TITLE
"error_code": 17, "error_message": "InsufficientNetworkMod"

### ISSUE THREAD

**Issue by hongry18** [ripple/rippled#2280] opened 2017-11-27 00:37 UTC
request
curl -X GET \
http://localhost:5005 \
-H 'Content-Type: application/json' \
-d '{
    "method": "account_info",
    "params": [
        {
            "account": "rBG...27b",
            "strict": true,
            "ledger_index": "current",
            "queue": true
        }
    ]
}'

response
{
    "result": {
        "error": "noNetwork",
        "error_code": 17,
        "error_message": "InsufficientNetworkMode",
        "request": {
            "account": "rBG...27b",
            "command": "account_info",
            "ledger_index": "current",
            "queue": true,
            "strict": true
        },
        "status": "error"
    }
}

server_info

{
    "result": {
        "info": {
            "build_version": "0.80.0",
            "closed_ledger": {
                "age": 15,
                "base_fee_xrp": 1e-05,
                "hash": "13FB...817",
                "reserve_base_xrp": 200,
                "reserve_inc_xrp": 50,
                "seq": 29
            },
            "complete_ledgers": "empty",
            "hostid": "localhost",
            "io_latency_ms": 1,
            "last_close": {
                "converge_time_s": 1.999,
                "proposers": 0
            },
            "load": {
                "job_types": [
                    {
                        "in_progress": 1,
                        "job_type": "clientCommand"
                    }
                ],
                "threads": 8
            },
            "load_factor": 1,
            "network_ledger": "waiting",
            "peers": 0,
            "pubkey_node": "n9M...4AXg",
            "pubkey_validator": "none",
            "published_ledger": "none",
            "server_state": "full",
            "state_accounting": {
                "connected": {
                    "duration_us": "48017447",
                    "transitions": 1
                },
                "disconnected": {
                    "duration_us": "1160612",
                    "transitions": 1
                },
                "full": {
                    "duration_us": "902968886",
                    "transitions": 1
                },
                "syncing": {
                    "duration_us": "0",
                    "transitions": 0
                },
                "tracking": {
                    "duration_us": "0",
                    "transitions": 0
                }
            },
            "uptime": 952,
            "validation_quorum": 5
        },
        "status": "success"
    }
}

the same happens with all request

**Comment by SneakyFish5** [comment] 2017-11-27 03:30
Noticed that “reserve_base_xrp” says “200”. It’s supposed to be 20.

**Comment by JoelKatz** [comment] 2017-11-27 05:41
You server has no peers. Most likely, it's a network connectivity problem but it could also be that it's not configured correctly.

**Comment by bachase** [comment] 2017-12-01 14:44
Closing this for now. If you are still having trouble after fixing networking connectivity issues, please open a new request with more details.

**Closed by bachase** 2017-12-01 14:44 UTC

**Comment by 0x49D1** [comment] 2017-12-04 11:19
I have same problem:

{
   "id" : 1,
   "result" : {
      "error" : "noNetwork",
      "error_code" : 17,
      "error_message" : "InsufficientNetworkMode",
      "request" : {
         "account" : "r.....Cn",
         "command" : "account_info"
      },
      "status" : "error"
   }
}
server_info:
{
   "id" : 1,
   "result" : {
      "info" : {
         "build_version" : "0.80.0",
         "closed_ledger" : {
            "base_fee_xrp" : 1e-05,
            "hash" : "517....9",
            "reserve_base_xrp" : 200,
            "reserve_inc_xrp" : 50,
            "seq" : 10
         },
         "complete_ledgers" : "empty",
         "hostid" : "ip....3",
         "io_latency_ms" : 1,
         "last_close" : {
            "converge_time_s" : 1.999,
            "proposers" : 5
         },
         "load" : {
            "job_types" : [
               {
                  "job_type" : "untrustedProposal",
                  "per_second" : 21
               },
               {
                  "in_progress" : 2,
                  "job_type" : "ledgerData",
                  "waiting" : 4
               },
               {
                  "in_progress" : 1,
                  "job_type" : "clientCommand"
               },
               {
                  "job_type" : "transaction",
                  "per_second" : 5
               },
               {
                  "job_type" : "fetchTxnData",
                  "per_second" : 6
               },
               {
                  "avg_time" : 8,
                  "job_type" : "trustedValidation",
                  "peak_time" : 46,
                  "per_second" : 1
               },
               {
                  "job_type" : "writeObjects",
                  "peak_time" : 4,
                  "per_second" : 2
               },
               {
                  "avg_time" : 3,
                  "job_type" : "acceptLedger",
                  "peak_time" : 9
               },
               {
                  "job_type" : "trustedProposal",
                  "per_second" : 1
               },
               {
                  "job_type" : "peerCommand",
                  "per_second" : 346
               },
               {
                  "job_type" : "diskAccess",
                  "peak_time" : 1,
                  "per_second" : 1
               },
               {
                  "avg_time" : 18,
                  "job_type" : "SyncReadNode",
                  "peak_time" : 228,
                  "per_second" : 1
               },
               {
                  "job_type" : "AsyncReadNode",
                  "peak_time" : 45,
                  "per_second" : 2710
               },
               {
                  "job_type" : "WriteNode",
                  "per_second" : 2
               }
            ],
            "threads" : 8
         },
         "load_factor" : 1,
         "network_ledger" : "waiting",
         "peers" : 10,
         "pubkey_node" : "n9...P",
         "pubkey_validator" : "none",
         "published_ledger" : "none",
         "server_state" : "connected",
         "state_accounting" : {
            "connected" : {
               "duration_us" : "22728764",
               "transitions" : 1
            },
            "disconnected" : {
               "duration_us" : "1274750",
               "transitions" : 1
            },
            "full" : {
               "duration_us" : "0",
               "transitions" : 0
            },
            "syncing" : {
               "duration_us" : "0",
               "transitions" : 0
            },
            "tracking" : {
               "duration_us" : "0",
               "transitions" : 0
            }
         },
         "uptime" : 24,
         "validation_quorum" : 3
      },
      "status" : "success"
   }
}   
Restarted rippled and it helped for some time, but now the problem is back again; network and accesses on the server are fine. But there is high CPU usage by rippled process..  Server has 4 Core Xeon and not that much transactions to deal with, so don't know from where is there such a high load.

**Comment by bachase** [comment] 2017-12-06 16:07
Based on the output above, I don't see an explanation for why you had high CPU usage and a delay syncing to the network.  Feel free to re-open the issue if you experience a similar problem and we can try to iterate on the root cause.

**Comment by 0x49D1** [comment] 2017-12-06 18:30
The problem was that the server could not keep up with ledger synchronizations: rippled started and looped in restart after 1 minute interval, debug log was showing that it was trying to keep up with ledger versions, but could not finish the process; then re-initialization again... Even after upgrading AWS EC2 instance to higher specs - there still was a problem. After that we've deleted the local database and tried to start from scratch. That helped, even downgrading the instance kept the syncs without problems. So now I have lost local ledger history before the time of the last start, but that is way smaller problem then completely stopped service.

**Comment by bachase** [comment] 2017-12-06 18:32
What type of EC2 instances are you using? Are you using NuDB backend or RocksDB?

**Comment by 0x49D1** [comment] 2017-12-06 18:33
RockDB and instance was t2.xlarge. Changed to c3.large in the end.

**Comment by bachase** [comment] 2017-12-06 18:34
Thanks.  Did it ever actually crash? Any ERR messages in the logs?

**Comment by bachase** [comment] 2017-12-06 18:35
I see you are ok for now; no need to respond if you don't want to.

**Comment by 0x49D1** [comment] 2017-12-06 18:43
I was checking debug log, can't really remember if it had ERR messages, but there were many messages like:  
NetworkOPs:WRN We are not running on the consensus ledger  
I know that this on is typically normal and we must wait for getting to the consensus, but I was waiting more than an hour + restarted the rippled and tried to wait again with no luck. The old log is rewritten now, so can't really recheck to answer properly.
