### ISSUE TITLE
Some ModifiedNode with AccountRoot can't know modify content

### ISSUE THREAD

**Issue by jingniao** [ripple/rippled#3420] opened 2020-05-29 00:52 UTC
I find some transaction has ModifiedNode for AccountRoot like 
`https://livenet.xrpl.org/transactions/410FB90681203BD29280539A9EF24EFDE07C8C7652A2428BCCBDACFCD0D57981/raw`
it modify LedgerIndex `BF1F2A23D614916E3C6ED2DCC389468CFA09045BEDB54C71A05C5E94EA6C6CFE` but I can't find what content is modified by this?

**Comment by nbougalis** [comment] 2020-05-29 22:14
Thank you for reporting this. We will take a look at this. Preliminary guess is that this is an account that had an offer deleted. A `FinalFields` should have bee included; we'll need to figure out why it isn't.

**Comment by nbougalis** [comment] 2020-05-29 22:27
The referenced object is an `AccountRoot` for [`rhub8VRN55s94qWKDv6jmDy1pUykJzF3wq`](https://livenet.xrpl.org/accounts/rhub8VRN55s94qWKDv6jmDy1pUykJzF3wq). It's the issuer of currencies used in this transaction.

There is a modification of a `DirectoryNode` associated with that address:

```
      {
        "ModifiedNode": {
          "FinalFields": {
            "Flags": 0,
            "IndexPrevious": "0000000000001BF4",
            "Owner": "rhub8VRN55s94qWKDv6jmDy1pUykJzF3wq",
            "RootIndex": "D7AC7D74720E29A563100F2B494BADB198F8A9E9FA46F57AE07123151E0DFA7A"
          },
          "LedgerEntryType": "DirectoryNode",
          "LedgerIndex": "D1E054A0E0CD2043B732EA1EEF2B8F93A77E699EE7AD922031186F636A889C95"
        }
      }
```

I suspect that the account root is being referenced by the threading code (i.e. it's trying to update the `PreviousTxnID` and `PreviousTxnLgrSeq` fields) without making any further modifications to the `AccountRoot`. Despite that, a `FinalFields` containing (at a minimum) the address of the account should be included.

We will treat this as a bug and try to understand why it occurred. Thank you for the report.

**Comment by JoelKatz** [comment] 2020-06-01 01:32
Nik and I took a pretty close look at node 8:

```
{
  "ModifiedNode": {
    "LedgerEntryType": "AccountRoot",
    "LedgerIndex": "BF1F2A23D614916E3C6ED2DCC389468CFA09045BEDB54C71A05C5E94EA6C6CFE",
    "PreviousTxnID": "B7148DD205EED3D0CB75F1157ADB4AF031162881904988507836E279E47D106C",
    "PreviousTxnLgrSeq": 55777253
  }
}
```

This record exists because an offer owned by this account was removed. The `PreviousTxnID` and `PreviousTxnLgrSeq` fields are here to prevent the loss of the end of the thread of executed transactions that affected that offer. The offer is removed from the ledger by this transaction, so the metadata needs to preserve the end of thread.

The number of owned objects wasn't affected because removing the offer decreased it by one. But the account didn't have a trust line for the acquired asset, so that increased it by one.

Because this record exists solely to prevent the loss of the end of the thread and is intended to be used only by someone walking from the account root, it contains no information not useful for that purpose. If not for the need to preserve the end of thread, it would not exist at all.

So that record is a surprising consequence of the current metadata rules and not a bug.

**Comment by nbougalis** [comment] 2020-06-04 07:09
@jingniao, unless you have any further questions, I'd like to go ahead and close this issue. I am taking, as action items, the need for better documentation about the metadata.

**Closed** 2020-06-08 01:16 UTC
Labels: Bug

**Comment by Godwin1961** [comment] 2020-08-03 16:25
PLEASE WHAT CAN BE DONE ABOUT THIS, THE RIPPLE SENT IS NOT REFLECTING AND IT HAS NOT BE RETRACTED
05C135F5DE71E396373E0D6DE44E77C955A3FCDA3918B72A5246937F0C11EC21
 GO
DESCRIPTIONRAW
STATUS:
This transaction failed with a status code of tecUNFUNDED_PAYMENT, and validated in ledger 57248130 on August 2, 2020 10:52 PM UTC.
DESCRIPTION:
This is a Payment transaction.
The payment is from rHxsZo42NrTq1hC9dcnS8KAuvc8LrNdbpn to rsRy14FvipgqudiGmptJBhr1RtpsgfzKMM.
The payment has a destination tag: 1736847995
It was instructed to deliver 68.5143 XRP.
The transaction's sequence number is 610
MEMOS:
The transaction has no memos.
TRANSACTION COST:
Sending this transaction consumed 0.000012 XRP.
FLAGS:
The transaction specified the following flags:
tfFullyCanonicalSig
AFFECTED LEDGER NODES:
It affected 1 nodes in the ledger:
MODIFIED NODES:
It modified the AccountRoot node of rHxsZo42NrTq1hC9dcnS8KAuvc8LrNdbpn
Balance reduced by 0.000012 from 27.30687 to 27.306858 XRP
