### ISSUE TITLE
Openssl 1.1.1 incompatibility

### ISSUE THREAD

**Issue by robcat** [ripple/rippled#2719] opened 2018-10-14 15:42 UTC
On archlinux, Openssl 1.1.1 is found but rejected by cmake, even if its version is greater than the specified minimum (1.0.2).
Openssl 1.0.2.p is also installed in parallel (via the official package openssl-1.0), but not automatically detected.

Rippled affected version: 1.1.0 and develop-tip 

```
  Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
  system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY)
  (found suitable version "1.1.1", minimum required is "1.0.2")
```

**Comment by MarkusTeufelberger** [comment] 2018-10-14 15:57
Are you sure that it's not their change to build a statically linked version by default (and Arch's "great" decision not to ship static libraries at all)? I had the same problems on Manjaro, try to add `-Dstatic=OFF` to the initial cmake call...

**Comment by MarkusTeufelberger** [comment] 2018-10-14 16:02
In fact the only builds that seem to semi-reliably work currently using only distro packages for dependencies are Arch nonstatic, Opensuse Tumbleweed nonstatic and Ubuntu 18.10 static and nonstatic. (https://github.com/MarkusTeufelberger/rippled-distrotest). I hope that Alpine edge nonstatic will start working (or at least fail elsewhere) once #2712 lands.

The error message is less than helpful, I'm not sure though if that's the fault of cmake (it would be much easier to spot if it said `libssl.a not found` for example) or the way it is used in this repo.

**Comment by MarkusTeufelberger** [comment] 2018-10-14 16:28
In case you want to reproduce:

Static (default) Arch build of 1.2.0-rc3: https://travis-ci.org/MarkusTeufelberger/rippled-distrotest/jobs/441293994
Nonstatic (otherwise default) Arch build of 1.2.0-rc3: https://travis-ci.org/MarkusTeufelberger/rippled-distrotest/jobs/441294015

Dockerfiles are in the repo mentioned above.

**Comment by mellery451** [comment] 2018-10-15 15:16
I think @MarkusTeufelberger is correct - this error message is the result of not having the static openssl libraries. Those deceptive/confusing error messages come from CMake's `find_package_handle_standard_args` which `FindOpenSSL` is invoking. `-Dstatic=OFF` is how you force our build to use dynamic boost/openssl/protobuf.

**Comment by nbougalis** [comment] 2018-11-01 14:33
Should we close this issue? Is this something actionable on our end, @mellery451?

**Comment by mellery451** [comment] 2018-11-01 15:20
I think we should close this issue. We could consider contributing a patch to the FindOpenSSL module (in CMake) that improves the diagnostic messaging around static libs. FWIW, I think [this issue](https://gitlab.kitware.com/cmake/cmake/issues/16885) might be related as well. There are a handful of other issues reported against that Find module, so it's not completely bulletproof.

**Comment by mDuo13** [comment] 2019-08-02 01:41
It might be worth mentioning in documentation that to build successfully on Arch, Majaro, and possibly others, you have to do `-Dstatic=OFF` since you won't have the static libs. But otherwise, yeah, closing this issue.

**Closed by mDuo13** 2019-08-02 01:41 UTC
