### ISSUE TITLE
lost my xrp

### ISSUE THREAD

**Issue by SP1305** [ripple/rippled#2318] opened 2018-01-04 19:29 UTC
I was translated ripples from the Bitfinex, But they not coming on my ripple desktop wallet. We sent a request to the Bitfinix support service, they answered that the problem was with the receiving party. Help me please 
my ripple wallet : rsgWtPXiZcq2Ftcowb6SaCSpdNuG9RXCFP

Transaction :16D73C043B8906FDF5C9C0192AB9B16FEA94140FB582F8590017D66EE7B664CF

Thanks.

**Comment by sublimator** [comment] 2018-01-04 19:38
You tried to send too much ...

You need to leave roughly speaking 20 - 50 XRP in your account as a reserve
...

**Comment by ximinez** [comment] 2018-01-04 19:38
https://xrpcharts.ripple.com/#/transactions/16D73C043B8906FDF5C9C0192AB9B16FEA94140FB582F8590017D66EE7B664CF

```
This transaction failed with a status code of tecUNFUNDED_PAYMENT, and validated in ledger 35231580 on December 22, 2017 5:45 PM.
```

Basically, the account that tried to send you 2700 XRP (`rLW9gnQo7BQhU6igk5keqYnH3TVrCxGRzm`) did not have 2700 XRP to send. Because the transaction was well formed and properly signed, the fee was charged, but that was the only effect.

**Comment by SP1305** [comment] 2018-01-04 19:51
in account rLW9gnQo7BQhU6igk5keqYnH3TVrCxGRzm
been 4,434.57 xrp
![img_3789](https://user-images.githubusercontent.com/35078856/34581525-61df2e94-f199-11e7-8098-166638792be5.JPG)

I have print screen

**Comment by SP1305** [comment] 2018-01-04 20:24
why in bitfinex that transaction complete ?
![2017-12-30-photo-00000097](https://user-images.githubusercontent.com/35078856/34582658-58e659e4-f19d-11e7-8412-7d514621461d.jpg)

in wallet(rLW9gnQo7BQhU6igk5keqYnH3TVrCxGRzm)who sent me 2700rxp, have in account 4434rxp
![1515097253802946](https://user-images.githubusercontent.com/35078856/34582773-cbdcfb06-f19d-11e7-804e-e6267b0313fa.jpg)

who can help me with this problem?
I wrote in rippex help center, but he don't answer....

**Comment by SP1305** [comment] 2018-01-04 20:30
why in bitfinex that transaction complete ?

in wallet(rLW9gnQo7BQhU6igk5keqYnH3TVrCxGRzm)who sent me 2700rxp, have in account 4434rxp[1515097253802946.jpg]
who can help me with this problem?
I wrote in rippex help center, but he don't answer....
.

**Comment by ximinez** [comment] 2018-01-04 21:11
If the exchange (Bitfinex) is showing a different balance than the XRP Ledger, then the problem is with the exchange. I'm sorry, but there's nothing else I can help you. Perhaps showing them this exchange will make them realize the transaction failed, but I have absolutely no control over what they do on their system.

I'm going to close this issue, since it doesn't appear to be related to rippled. If any further information points to a problem with rippled, feel free to reopen it.

**Comment by HowardHinnant** [comment] 2018-01-04 21:12
At the time the transaction took place (December 22, 2017 5:45 PM) the balance of rLW9gnQo7BQhU6igk5keqYnH3TVrCxGRzm was 2,711.639485, which was insufficient to send 2700 because of the required reserve that @ximinez mentions above.  The 2700 _was not_ transferred, at least not by transaction 16D73C043B8906FDF5C9C0192AB9B16FEA94140FB582F8590017D66EE7B664CF.

**Closed by ximinez** 2018-01-04 21:11 UTC
