### ISSUE TITLE
Missing node errors

### ISSUE THREAD

**Issue by donovanhide** [ripple/rippled#2299] opened 2017-12-15 18:56 UTC
```
2017-Dec-15 18:55:44 Protocol:WRN [242542] getNodeFat( NodeID(3,9AD0000000000000000000000000000000000000000000000000000000000000)) throws exception: AS node
2017-Dec-15 18:55:44 Protocol:WRN [242542] getNodeFat( NodeID(50,BC05A0B94DB6C7C0B2D9E04573F0463DC15DB8033ABA85624E00000000000000)) throws exception: AS node
2017-Dec-15 18:55:44 Protocol:WRN [242542] getNodeFat( NodeID(50,ED1FD00FD76075C8AAEBB0C24A43A48BB1FF74A2B334BBDB4F00000000000000)) throws exception: AS node
2017-Dec-15 18:55:44 Protocol:WRN [242542] getNodeFat( NodeID(5,EDA2000000000000000000000000000000000000000000000000000000000000)) throws exception: AS node
2017-Dec-15 18:55:44 Protocol:WRN [242542] getNodeFat( NodeID(50,02BAAC1E67C1CE0E96F0FA2E8061020536CEDD043FEB0FF54F00000000000000)) throws exception: AS node
2017-Dec-15 18:55:44 Protocol:WRN [242542] getNodeFat( NodeID(50,6CBBA821BB26420284E9C91F4E8B5D66FA66DDB55163D1F54A00000000000000)) throws exception: AS node
2017-Dec-15 18:55:44 Ledger:ERR Missing node in 34980547
2017-Dec-15 18:55:44 Protocol:WRN [242542] getNodeFat( NodeID(5,D471B00000000000000000000000000000000000000000000000000000000000)) throws exception: AS node
2017-Dec-15 18:55:44 Protocol:WRN [242542] getNodeFat( NodeID(5,0C57E00000000000000000000000000000000000000000000000000000000000)) throws exception: AS node
2017-Dec-15 18:55:44 Protocol:WRN [242542] getNodeFat( NodeID(5,1F79900000000000000000000000000000000000000000000000000000000000)) throws exception: AS node
2017-Dec-15 18:55:44 Protocol:WRN [242542] getNodeFat( NodeID(3,1030000000000000000000000000000000000000000000000000000000000000)) throws exception: AS node
2017-Dec-15 18:55:44 Protocol:WRN [242542] getNodeFat( NodeID(50,2FC6C01291733160ABD53BC7D54C4E733B868BA81C982BFA4D00000000000000)) throws exception: AS node
2017-Dec-15 18:55:44 Protocol:WRN [242542] getNodeFat( NodeID(5,40E8A00000000000000000000000000000000000000000000000000000000000)) throws exception: AS node
2017-Dec-15 18:55:44 Protocol:WRN [242542] getNodeFat( NodeID(50,7035F45D0D6677B54720F2A9CBD0EA1155313D0F038A9E5B5E00000000000000)) throws exception: AS node
2017-Dec-15 18:55:44 Protocol:WRN [242542] getNodeFat( NodeID(5,7254400000000000000000000000000000000000000000000000000000000000)) throws exception: AS node
```
Getting lots of these when running 0.80.1.

**Comment by sublimator** [comment] 2017-12-15 18:59
Sad!!

**Comment by JoelKatz** [comment] 2017-12-15 21:01
This is usually caused by a back end database (NuDB or RocksDB) that doesn't have a ledger that the SQLite databases say the server has. It can be caused by deleting the node database and not the SQLite databases. The server should sanely handle this by updating its recording of what ledgers it has.

**Comment by donovanhide** [comment] 2017-12-15 21:25
I haven't deleted the node database in months, thanks to online_delete, and when I did, I removed the sqlite database at the same time. The ledger is 34980547, which is recent, so bit confused by your explanation. Is it likely to be nodes which have been unchanged for many moons which have suddenly been touched by the recent circumstances that are missing?

**Comment by JoelKatz** [comment] 2017-12-15 21:45
That's kind of puzzling. It's theoretically possible that other servers are asking you for nodes in ledgers that you just don't have. There's nothing preventing any server from asking any other server for any ledger -- even a ledger that was never valid on the network. But honestly that does seem like a fairly unlikely explanation.

**Comment by donovanhide** [comment] 2017-12-15 21:48
My guess it is another peer which is retrieving historical ledgers and asking my peer for them. When it tries to get the nodes, it can't find them, even though they might be in the sqlite db. You can see the pattern of ever further back ledger sequences in the log:
```
2017-Dec-15 21:44:54 Protocol:WRN [242542] getNodeFat( NodeID(53,4FF2FFF23E57A8B23DF960BBA0333A4A78A070D320C6C93C5405500000000000)) throws exception: AS node
2017-Dec-15 21:44:54 Protocol:WRN [242542] getNodeFat( NodeID(53,54E85B82AA0DEFF4CBF7A3A21D5525484B10185C75FE10215405500000000000)) throws exception: AS node
2017-Dec-15 21:44:55 Ledger:ERR Missing node in 34977555
2017-Dec-15 21:44:55 Protocol:WRN [242542] getNodeFat( NodeID(3,1C00000000000000000000000000000000000000000000000000000000000000)) throws exception: AS node
2017-Dec-15 21:44:55 Protocol:WRN [242542] getNodeFat( NodeID(3,2390000000000000000000000000000000000000000000000000000000000000)) throws exception: AS node
2017-Dec-15 21:44:55 Protocol:WRN [242542] getNodeFat( NodeID(5,2521400000000000000000000000000000000000000000000000000000000000)) throws exception: AS node
2017-Dec-15 21:44:57 Ledger:ERR Missing node in 34977554
2017-Dec-15 21:44:57 Protocol:WRN [242542] getNodeFat( NodeID(5,CAB8F00000000000000000000000000000000000000000000000000000000000)) throws exception: AS node
2017-Dec-15 21:44:57 Protocol:WRN [242542] getNodeFat( NodeID(5,154D400000000000000000000000000000000000000000000000000000000000)) throws exception: AS node
2017-Dec-15 21:44:57 Protocol:WRN [242542] getNodeFat( NodeID(7,F494F07000000000000000000000000000000000000000000000000000000000)) throws exception: AS node
2017-Dec-15 21:44:57 Protocol:WRN [242542] getNodeFat( NodeID(7,14B232A000000000000000000000000000000000000000000000000000000000)) throws exception: AS node
2017-Dec-15 21:44:57 Protocol:WRN [242542] getNodeFat( NodeID(7,159D72E000000000000000000000000000000000000000000000000000000000)) throws exception: AS node
2017-Dec-15 21:45:20 Ledger:ERR Missing node in 34977548
2017-Dec-15 21:45:20 Protocol:WRN [242542] getNodeFat( NodeID(3,F990000000000000000000000000000000000000000000000000000000000000)) throws exception: AS node
2017-Dec-15 21:45:20 Protocol:WRN [242542] getNodeFat( NodeID(3,2480000000000000000000000000000000000000000000000000000000000000)) throws exception: AS node
2017-Dec-15 21:45:20 Protocol:WRN [242542] getNodeFat( NodeID(3,44E0000000000000000000000000000000000000000000000000000000000000)) throws exception: AS node
2017-Dec-15 21:45:20 Protocol:WRN [242542] getNodeFat( NodeID(3,5C10000000000000000000000000000000000000000000000000000000000000)) throws exception: AS node
2017-Dec-15 21:45:20 Protocol:WRN [242542] getNodeFat( NodeID(3,C380000000000000000000000000000000000000000000000000000000000000)) throws exception: AS node
2017-Dec-15 21:45:20 Ledger:ERR Missing node in 34977546
2017-Dec-15 21:45:20 Protocol:WRN [242542] getNodeFat( NodeID(3,1D50000000000000000000000000000000000000000000000000000000000000)) throws exception: AS node
2017-Dec-15 21:45:20 Protocol:WRN [242542] getNodeFat( NodeID(3,2480000000000000000000000000000000000000000000000000000000000000)) throws exception: AS node
2017-Dec-15 21:45:20 Protocol:WRN [242542] getNodeFat( NodeID(3,44E0000000000000000000000000000000000000000000000000000000000000)) throws exception: AS node
2017-Dec-15 21:45:20 Protocol:WRN [242542] getNodeFat( NodeID(3,5C10000000000000000000000000000000000000000000000000000000000000)) throws exception: AS node
2017-Dec-15 21:45:20 Protocol:WRN [242542] getNodeFat( NodeID(3,C3
```
I'm guessing that the online_delete hasn't correctly removed references to the old nodes from the previous generation in the sqlite db? Whatever the cause, it certainly fills up the log file.

**Comment by donovanhide** [comment] 2017-12-15 21:53
Here's a possible lead. I have online_delete set to 50000, but my server is advertising:
```
....
         "complete_ledgers" : "34973434-35056448",
...
```
Which is a range greater than 50,000, which explains why the nodes don't exist. I guess the bug is the advertised ledger range is incorrect.

**Comment by nbougalis** [comment] 2018-11-01 03:32
Thanks. We'll look into the issue with the `complete_ledgers` mismatch vs. online delete and address this. Closing this issue at this point since it's rather old.

**Closed by nbougalis** 2018-11-01 03:32 UTC
